name: Go Build

on:
  push:
    branches:
      - "master"
    paths:
      - "src/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "src/**"
      - ".github/workflows/**"

jobs:
  lint:
    name: Go lint
    if: "!contains(toJSON(github.event.commits.*.message), '[SKIP BUILD]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup the Golang environment with version 1.20.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.x

      - name: Run lint
        working-directory: ./src
        run: go mod tidy && go mod vendor && go vet ./...

  build:
    name: Build
    if: "!contains(toJSON(github.event.commits.*.message), '[SKIP BUILD]')"
    needs: lint
    runs-on: ubuntu-latest
    
    strategy:
        fail-fast: true
        matrix:
            os: ["linux", "darwin", "windows"]
            arch: ["x86", "x64", "arm", "arm64"]
            config: ["debug", "release"]
    
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v3

      - name: Setup the Golang environment with version 1.20.x
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x

      - name: Run the build-<config>-<arch> make target
        run: make build-${{ matrix.config }}-${{ matrix.arch }} GOOS=${{ matrix.os }}
        