name: Go Test

on:
  push:
    branches:
      - "master"
    paths:
      - "src/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "src/**"
      - ".github/workflows/**"

jobs:
  test:
    name: Go Test
    if: "!contains(toJSON(github.event.commits.*.message), '[SKIP TEST]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup the Golang environment with version 1.20.x
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x

      - name: Run Test
        run: make test
